---
title: "vignette_flow"
output: html_document
---


## Including Plots


```{r tidyverse, echo=FALSE}
plots <- data$vst_perplotperyear %>% 
  dplyr::filter(treesPresent == "Y") %>%
  dplyr::select(plotID, siteID, easting, northing, utmZone)
```
```{r tidyverse, echo=FALSE}
plt = readr::read_csv("//blue/ewhite/s.marconi/Chapter3/neonVegWrangleR/indir//vst_top_canopy.csv")
#plt_2019 = plots %>% filter(siteID %in% c("BONA", "DELA", "NIWO", "CLBJ"))
dt <- split.data.frame(plt, f = plt$siteID)
library(parallel)
# Calculate the number of cores
no_cores <- 5
# Initiate cluster
cl <- makeCluster(no_cores)
parLapply(cl = cl, dt, retrieve_aop_data)
stopCluster(cl)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r tidyverse, echo=FALSE}

plt = readr::read_csv("//blue/ewhite/s.marconi/Chapter3/neonVegWrangleR/indir/neon_vst_data_022021.csv")

for(yr in unique(plt$year)){
  tmp = plt %>% filter(year == yr)
  crop_data_to_plot(plt= plt, target_year = yr, bff=20, parallelized =F)
}

#crop_data_to_plot(plt= plt, bff=12, tasks = 32)

```





